### ISSUE TITLE
paragraph tag just breaks line

### ISSUE THREAD

**Issue by ispiropoulos** [TanguyAladenise/EMString#1]
Hello and thank you for the Awesome EMString!

On your screenshots, I see that on paragraphs the EMString is acting as usual, starting a new paragraph.

I am doing this on a test project (Swift) and is just changing lines. Am I doing something wrong or is it a bug?

code: http://i.imgur.com/f4BasDd.png

simulator: http://i.imgur.com/8go1KrX.png

Greetings from Greece!

**Comment by TanguyAladenise** [comment]
Hi,

Actually it is "normal". < p> break the line but does not add a default space between paragraphs. I hesitated to. Might be something I change in the future. 
The thing is I have a little "bug" in my sample project apparently. If you like at the code in the view controller you will see that I added a \n after <\p>. Which explains why you have the paragraph jump. The bug being the deactivated view of my sample project not showing those \n. Which is kind of normal. 

Hope it helps you and that you are enjoying the repo :).
